### ISSUE TITLE
RTL is wrong 

### ISSUE THREAD

**Issue by KindDistribution376** [CatenaryMaps/catenary-landing#7]
Hey! Hebrew and arabic speaker here. I'd start by saying it's a really cool project. Seems rather useful. I checked my home country (but it holds for any country in the middle east) and saw this ->
![image](https://github.com/CatenaryMaps/catenary-landing/assets/118935490/76baf1ce-a07b-48ae-be1f-dd4fe869b267)

Now, I guess the source of the issue is non of the developers speaks some rtl language and it was probably misesed, but the rtl is written terribly. Say here, 
![image](https://github.com/CatenaryMaps/catenary-landing/assets/118935490/36c2e890-a6f1-4535-94e6-6a10f4a7389d)
That's the city of Ashkelon, which is written in hebrew as אשקלון. However, it is marked in your project as ןולקשא. 

Please fix 👍

**Comment by jktrn** [comment]
@kylerchin

**Comment by kylerchin** [comment]
Hello! This issue belongs in https://github.com/CatenaryMaps/catenary-frontend/. I'll implement RTL.

**Comment by kylerchin** [comment]
This issue is now resolved, closing
